version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=testroot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - PLACE=DOCKER
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - XAPIKEY=f60ad03e-2be5-4a42-8c01-0454f0055008
      - PLACE=DOCKER
